### ISSUE TITLE
build.sh failure

### ISSUE THREAD

**Issue by jackyangNJ** [NetSys/NetBricks#91]
#Hi all,
  I was build the NetBricks using Rust nightly version. When I run _build.sh_, however when compiling e2d2 v0.2.0 and DPDK bindings, an error occurred. The log is as below. Thanks!
```
   Compiling e2d2 v0.2.0 (file:///home/tian/NetBricks/framework)
error: failed to run custom build command for `e2d2 v0.2.0 (file:///home/tian/NetBricks/framework)`
process didn't exit successfully: `/home/tian/NetBricks/target/release/build/e2d2-c9809f4dab260928/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/home/tian/NetBricks/3rdparty/dpdk/build/lib
cargo:rustc-link-search=native=/home/tian/NetBricks/target/native
Header path Some("/home/tian/NetBricks/framework/src/native_include/dpdk-headers.h")

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
When I use apt-get install libclang, errors are like this:

```
Compiling e2d2 v0.2.0 (file:///home/tian/NetBricks/framework)
error: failed to run custom build command for `e2d2 v0.2.0 (file:///home/tian/NetBricks/framework)`
process didn't exit successfully: `/home/tian/NetBricks/target/release/build/e2d2-c9809f4dab260928/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/home/tian/NetBricks/3rdparty/dpdk/build/lib
cargo:rustc-link-search=native=/home/tian/NetBricks/target/native
Header path Some("/home/tian/NetBricks/framework/src/native_include/dpdk-headers.h")

--- stderr
/usr/local/lib/clang/7.0.0/include/xmmintrin.h:2968:44: error: token is not a valid binary operator in a preprocessor subexpression
/usr/local/lib/clang/7.0.0/include/emmintrin.h:1414:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/local/lib/clang/7.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int')
/usr/local/lib/clang/7.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int')
/usr/local/lib/clang/7.0.0/include/xmmintrin.h:2968:44: error: token is not a valid binary operator in a preprocessor subexpression, err: true
/usr/local/lib/clang/7.0.0/include/emmintrin.h:1414:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/local/lib/clang/7.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int'), err: true
/usr/local/lib/clang/7.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int'), err: true
thread 'main' panicked at 'Unable to generate DPDK bindings: ()', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by apanda** [comment]
You need to install `clang`. I generally use clang-5.0 (`apt-get install clang-5.0`), but just tested with 7 which also seems to work. Alternately, you can build in a container by running `./build.sh build_container` in which case all the dependencies are included. Closing this issue, feel free to reopen if things don't work.

**Comment by cyz14** [comment]
> You need to install `clang`. I generally use clang-5.0 (`apt-get install clang-5.0`), but just tested with 7 which also seems to work. Alternately, you can build in a container by running `./build.sh build_container` in which case all the dependencies are included. Closing this issue, feel free to reopen if things don't work.

The image apanda:netbricks-build on https://hub.docker.com/u/apanda may be out-of-dated, I tried to pull and run it but it fails to run rustup update, I think it's because rustup could not rename file in overlayfs. 
Could you build a new one and release it ? I have some problem now so I cannot build one for myself. Thanks.
